
export const MUSIC_STATUS_PLAY = 'MUSIC_PLAY';
export const MUSIC_STATUS_PAUSE = 'MUSIC_PAUSE';
export const CHANGE_MUSIC_PLAY_STATUS = 'CHANGE_MUSIC_PLAY_STATUS';

export const CHANGE_MUSIC_PLAY_MODEL = 'CHANGE_MUSIC_PLAY_MODEL';
