
export const VIEW_BOTTOM_SHOW_MUSIC = 'BOTTOM_SHOW_MUSIC';
export const VIEW_BOTTOM_HIDDEN_MUSIC = 'BOTTOM_HIDDEN_MUSIC';
export const VIEW_BOTTOM_SHOW_PLAYLIST = 'BOTTOM_SHOW_PLAYLIST';
export const VIEW_BOTTOM_HIDDEN_PLAYLIST = 'BOTTOM_HIDDEN_PLAYLIST';
