
export const VIEW_BOTTOM_SHOW_MUSIC = 'BOTTOM_SHOW_MUSIC';
export const VIEW_BOTTOM_HIDDEN_MUSIC = 'BOTTOM_HIDDEN_MUSIC';

export const VIEW_BOTTOM_SHOW_PLAYLIST = 'BOTTOM_SHOW_PLAYLIST';
export const VIEW_BOTTOM_HIDDEN_PLAYLIST = 'BOTTOM_HIDDEN_PLAYLIST';

export const VIEW_BOTTOM_SHOW_MENU = 'BOTTOM_SHOW_MENU';
export const VIEW_BOTTOM_HIDDEN_MENU = 'BOTTOM_HIDDEN_MENU';

export const VIEW_MODAL_SHOW = 'MODAL_SHOW';
export const VIEW_MODAL_HIDDEN = 'MODAL_HIDDEN';
